from app.contracts import proposal_lifecycle_envelopes as _envelopes
from app.contracts import proposal_lifecycle_lineage as _lineage
from app.contracts import proposal_lifecycle_summary as _summary
from app.contracts import proposal_lifecycle_workflow as _workflow

ProposalApprovalsData = _workflow.ProposalApprovalsData
ProposalApprovalsEnvelopeResponse = _envelopes.ProposalApprovalsEnvelopeResponse
ProposalApprovalRecordData = _workflow.ProposalApprovalRecordData
ProposalCreateData = _envelopes.ProposalCreateData
ProposalCreateEnvelopeResponse = _envelopes.ProposalCreateEnvelopeResponse
ProposalLineageData = _lineage.ProposalLineageData
ProposalLineageEnvelopeResponse = _envelopes.ProposalLineageEnvelopeResponse
ProposalStateTransitionData = _envelopes.ProposalStateTransitionData
ProposalStateTransitionEnvelopeResponse = _envelopes.ProposalStateTransitionEnvelopeResponse
ProposalSummaryData = _summary.ProposalSummaryData
ProposalVersionData = _summary.ProposalVersionData
ProposalVersionEnvelopeResponse = _envelopes.ProposalVersionEnvelopeResponse
ProposalVersionLineageItemData = _lineage.ProposalVersionLineageItemData
ProposalWorkflowEventData = _workflow.ProposalWorkflowEventData
ProposalWorkflowEventsData = _workflow.ProposalWorkflowEventsData
ProposalWorkflowEventsEnvelopeResponse = _envelopes.ProposalWorkflowEventsEnvelopeResponse
