from typing import Any

RISK_CONCENTRATION_PAYLOAD_EXAMPLE: dict[str, Any] = {
    "portfolio_concentration": {
        "hhi_current": 1200.0,
        "hhi_proposed": 1225.0,
        "hhi_delta": 25.0,
    },
    "single_position_concentration": {
        "top_position_weight_current": 0.2,
        "top_position_weight_proposed": 0.21,
        "top_position_weight_delta": 0.01,
        "top_n_cumulative_weight_current": 0.5,
        "top_n_cumulative_weight_proposed": 0.52,
        "top_n_cumulative_weight_delta": 0.02,
        "top_n": 10,
        "top_position_current": {
            "security_id": "FO_FUND_PIMCO_INC",
            "security_name": "PIMCO GIS Income Fund",
            "weight": 0.2,
        },
        "top_position_proposed": {
            "security_id": "FO_FUND_PIMCO_INC",
            "security_name": "PIMCO GIS Income Fund",
            "weight": 0.21,
        },
    },
    "issuer_concentration": {
        "hhi_current": 1500.0,
        "hhi_proposed": 1600.0,
        "hhi_delta": 100.0,
        "top_issuer_weight_current": 0.25,
        "top_issuer_weight_proposed": 0.27,
        "top_issuer_weight_delta": 0.02,
        "coverage_status": "complete",
        "covered_position_count_current": 10,
        "covered_position_count_proposed": 10,
        "total_position_count_current": 10,
        "total_position_count_proposed": 10,
        "uncovered_position_count_current": 0,
        "uncovered_position_count_proposed": 0,
        "coverage_ratio_current": 1.0,
        "coverage_ratio_proposed": 1.0,
        "note": None,
        "top_issuer_current": {
            "issuer_id": "ULTIMATE_PIMCO",
            "issuer_name": "Pacific Investment Management Company LLC",
            "weight": 0.25,
        },
        "top_issuer_proposed": {
            "issuer_id": "ULTIMATE_PIMCO",
            "issuer_name": "Pacific Investment Management Company LLC",
            "weight": 0.27,
        },
    },
    "valuation_context": {
        "portfolio_currency": "USD",
        "reporting_currency": "USD",
        "position_basis": "market_value_base",
        "weight_basis": "total_market_value_base",
    },
    "execution_context": {
        "as_of_date": "2026-04-04",
        "portfolio_id": "PF_RISK_CONC",
        "simulation_session_id": None,
        "simulation_session_version": None,
        "session_expires_at": None,
        "issuer_grouping_level": "ultimate_parent",
        "enrichment_policy": "merge_caller_then_core",
        "include_cash_positions": True,
        "include_zero_quantity_positions": False,
    },
}
